// ===========================================================================
// <copyright file="ResiliencyPatterns.cs" company="Level Up Software">
// Copyright (c) Level Up Software. All rights reserved.
// </copyright>
// ===========================================================================

using lvlup.DataFerry.Utilities;

namespace lvlup.DataFerry.Properties;

/// <summary>
/// Defines the available pre-configured resilience patterns that can be generated by the <see cref="PollyPolicyGenerator"/> class.
/// </summary>
public enum ResiliencyPatterns
{
    /// <summary>
    /// Represents no specific resilience pattern, resulting in default behavior (e.g., only Timeout and Fallback).
    /// </summary>
    None = 0,

    /// <summary>
    /// Represents a basic resilience pattern which includes Timeout, Retry, and Fallback policies.
    /// </summary>
    Basic = 1,

    /// <summary>
    /// Represents an advanced resilience pattern which includes Timeout, Bulkhead Isolation, Retry, Circuit Breaker, and Fallback policies.
    /// </summary>
    Advanced = 2
}